### ISSUE TITLE
Updates to script to support resilient segmented archiving

### ISSUE THREAD

**Issue by anilmur** [bennage/lva-tbd#28]
One of the features in the newest build is segmented archiving, where the edge module will aggregate video for lengthy segments (eg. 15 minutes) before uploading that video as one large blob. This saves customers $$ in terms of transaction cost.

To support this, and to allow sporadic loss of network connectivity, we ask customers to create a local folder on the VM, and tell us how many GB we can write to it as a temp cache.

So we need the following update: Setup script should create a folder /var/local/mediaservices, and a subfolder /var/local/mediaservices/tmp

I used sudo mkdir while on the VM - so permissions show up as the following

lvaadmin@lva-sample-iot-edge-device:~$ ls -alF /var/local
total 12
drwxrwsr-x  3 root staff 4096 May  8 18:52 ./
drwxr-xr-x 13 root root  4096 May  8 18:51 ../
drwxr-sr-x  6 root staff 4096 May  8 19:30 mediaservices/

lvaadmin@lva-sample-iot-edge-device:~$ ls -alF /var/local/mediaservices/
total 12
drwxr-sr-x 6 root staff 4096 May  8 19:30 ./
drwxrwsr-x 3 root staff 4096 May  8 18:52 ../
drwxr-sr-x 3 root staff 4096 May  8 20:38 tmp

**Comment by bennage** [comment]
added
